version: '3.8'

services:
    web:
        build: .
        container_name: my-webserver
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "80:80"
        networks:
            - my-network
        depends_on:
            - db

    db:
        image: mysql:latest
        container_name: my-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3307:3306"  # Host port 3307 mapped to container port 3306
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - my-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: my-phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - my-network
        platform: linux/amd64

networks:
    my-network:

volumes:
    db_data:
